server:
  port: 9090

spring:
  profiles:
    #    active: release
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cinema
    username: root
    password: "00000000"


